# -*- coding: utf-8 -*-
"""RoomDecider.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uaxTKoZGO-qKCKKgHtZKY-gFoeXkz5eN
"""

class RoomDecider():
  def __init__(self, cards=[]):
    self.people = ['Rev Green', 'Colonel Mustard', 'Professor Plum', 'Mrs. Peacock',
      'Miss Scarlett', 'Mrs. White']
    self.weapons = ['Candlestick', 'Dagger', 'Lead Pipe', 'Revolver',
      'Rope', 'Wrench']
    self.rooms = ['Ballroom', 'Billiard Room', 'Conservatory', 'Dining Room',
      'Hall', 'Kitchen', 'Library', 'Lounge', 'Study']
    self.neighbors = {
        'Ballroom': ['Conservatory', 'Billiard Room', 'Dining Room', 'Kitchen'],
        'Billiard Room': ['Library', 'Conservatory', 'Ballroom'],
        'Conservatory': ['Ballroom', 'Billiard Room'],
        'Dining Room': ['Lounge', 'Ballroom', 'Hall'],
        'Hall': ['Study', 'Library', 'Dining Room', 'Lounge'],
        'Kitchen': ['Ballroom'],
        'Library': ['Billiard Room', 'Study', 'Hall'],
        'Lounge': ['Dining Room', 'Hall'],
        'Study': ['Hall', 'Library']
    }
    self.secret_passages = {
        'Conservatory': 'Lounge',
        'Lounge': 'Conservatory',
        'Kitchen': 'Study',
        'Study': 'Kitchen'
    }

    self.previous_room = 'None'

    self.known = []
    self.options = []

    for i in cards:
      if i in self.rooms:
        self.known += [i]
        self.options += [i]
    
    def nextRoom(currentRoom, madeSuggestion, roomKnown):

      if not madeSuggestion and (roomKnown and currentRoom in options or not roomKnown):
        return currentRoom
      
      for i in self.neighbors[currentRoom]:
        if roomKnown and i in options or not i in known or i in secret_passages
           and not secret_passages[i] in known:
          return i
      
      if next = self.previous_room: 
        next = sellf.neighbors[currentRoom][1]

      self.previous_room = currentRoom
        return next

